import streamlit as st

def faq_contents():
    st.title("Cryptocurrency Prediction: Frequently Asked Questions")
    with st.expander("What is Cryptocurrency?"):
        st.write("Cryptocurrency is a digital currency produced by a public network, rather than any government, that uses cryptography to make sure payments are sent and received safely.")
        st.caption("(source: *Oxford Dictionary*)")

    with st.expander("How Does Cryptocurrency Works?"):
        st.write("Cryptocurrencies run on a distributed public ledger named blockchain, that contains record of all transactions held by currency holders.")
        st.write("Units of cryptocurrency are generated by a mining process. Mining generates coin that involves complex mathematical problems.")
        st.write("Cryptocurrency owners does not hold anything tangible, all that exists is a key that allows the holder to move a record from one person to another without having third parties involved.")
        st.caption("(source: *kaspersky.com*)")

    with st.expander("Are cryptocurrencies considered a time series data?"):
        st.write("Yes, cryptocurrencies are often considered a time series data. The data consists of the price, volume, block reward, that recorded at regular intervals (such as day, hour, or minute).")

    with st.expander("What is time series?"):
        st.write("Time series is a sequence of data points that occur in successive order over some period of time.")
        st.caption("(source: *investopedia.com*)")

    with st.expander("What is time series forecasting?"):
        st.write("Time series forecasting is a technique for the prediction of events through a sequence of time. It predicts the future events based on the trends occur in the past, assuming that the future will hold a similar historical trends.")
        st.caption("(source: *influxdata.com*)")

    with st.expander("What is the example of a time series data?"):
        st.write("Examples of a time series data are:")
        st.write("1. Stock Prices")
        st.write("2. Cryptocurrency Prices")
        st.write("3. Heart Rate Monitoring")
